### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by Tobias-Glauser** [divtec-cejef/2023-CCH-PO-Circuit-et-API#214]

**Comment by drafolin** [comment]
@Tobias-Glauser Si t'as rien d'autre à faire tu peux essayer

**Comment by drafolin** [comment]
Monté max a 35% du CPU avec 200 concurrents, centré sur les routes de voitures et de sections de l'api

**Comment by drafolin** [comment]
Monté max a 11% avec 200 concurrents concentrés sur le front. Le goulot d'étranglement se situe au niveau du js et surtout du css qui sont énormes. Voir si il y a moyen de réduire la taille.

**Comment by drafolin** [comment]
La db ne monte jamais plus haut que 2% en CPU dans quelque stress test que ce soit.

**Comment by drafolin** [comment]
> Voir si il y a moyen de réduire la taille.


https://nginx.org/en/docs/http/ngx_http_gzip_module.html

**Comment by drafolin** [comment]
closed by #416
