### ISSUE TITLE
Model 3D ne s'affiche pas

### ISSUE THREAD

**Issue by Tobias-Glauser** [divtec-cejef/2023-CCH-PO-Circuit-et-API#479]
Le modèle 3D ne s'affiche pas sur la page d'accueil en display modern

1. Aller sur la page d'accueil

- [ ] Détecter la source de l'erreur
- [ ] Trouver une solution
- [ ] Implémenter une solution
- [ ] Tester la fonctionnalité
- [ ] Déployer le fix

**Comment by drafolin** [comment]
☺
